version: "2"
vars:
  ARGS: ""
  os:
    sh: go env GOOS
  arch:
    sh: go env GOARCH
  kbversion: 2.2.0
  kbdir: ./.kubebuilder

env:
  KUBEBUILDER_ASSETS: "{{.kbdir}}/bin"

tasks:
  lint:
    cmds:
      - golangci-lint run
    sources:
      - ./**/*.go

  test:
    desc: Run full test suite
    deps:
      - kubebuilder
    cmds:
      - go test -cover -coverprofile c.out ./...
    generates:
      - c.out
    sources:
      - ./**/*.go

  build:
    desc: Build binary
    cmds:
      - go build -o pomerium-operator cmd/pomerium-operator/*.go
    generates:
      - pomerium-operator
    sources:
      - ./**/*.go
      - ./go.mod
      - ./go.sum

  run:
    desc: Run in debug mode with $ARGS as arguments
    cmds:
      - go run cmd/pomerium-operator/*.go --debug "{{.ARGS}}"

  kubebuilder:
    desc: Install kubebuilder for testing
    cmds:
      - curl -L https://go.kubebuilder.io/dl/{{.kbversion}}/{{.os}}/{{.arch}} | tar -xz -C /tmp/
      - mv /tmp/kubebuilder_{{.kbversion}}_{{.os}}_{{.arch}} .kubebuilder
    status:
      - test -d "{{.kbdir}}/bin"
    generates:
      - "{{.kbdir}}/bin/*"

  clean:
    desc: Clean binary and kubebuilder
    cmds:
      - rm -rf .kubebuilder
      - rm -f pomerium-operator
      - rm -f coverage.txt
